import pandas as pd

question_cols = [
    "Variable: External: Q1: Gender",
    "Variable: External: Q2: Age (write-in)",
    "Variable: External: Q3: _ Urban/Rural (self-report)",
    "Variable: External: Q5: Annual Income (US)",
    "Variable: External: MainRegionName",
    "Variable: External: Food - Main Grocery Shop",
    ["Q3: _ Who do you grocery shop for?\nOption 1: Myself",
    "Q3: _ Who do you grocery shop for?\nOption 2: Partner or spouse",
    "Q3: _ Who do you grocery shop for?\nOption 3: Child or children",
    "Q3: _ Who do you grocery shop for?\nOption 4: Other family members",
    "Q3: _ Who do you grocery shop for?\nOption 5: Friends or neighbors",
    "Q3: _ Who do you grocery shop for?\nOption 6: ❌ I don't grocery shop"],
    "Q5: _ Number of people",
    "Q6: _ How often do you get groceries?",
    "Q7: _ How do you shop for groceries?",
    "Q8: _ Grocery shopping behavior",
    ["Q9: _ Finding best deals\nOption 1: I buy different items at different stores, e.g. I buy pantry staples f",
    "Q9: _ Finding best deals\nOption 2: Before shopping, I compare prices of items on my list between stores o",
    "Q9: _ Finding best deals\nOption 3: I keep track of how much items cost at different stores.",
    "Q9: _ Finding best deals\nOption 4: I use coupons at multiple stores.",
    "Q9: _ Finding best deals\nOption 5: I buy items on sale at different stores.",
    "Q9: _ Finding best deals\nOption 6: Other"],
    "Q10: _ Number of different stores bought groceries at in last 3 months",
    "Q11: _ Why buy in-store AND online",
    ["Q12: _ Factors in choosing where to shop\nOption 1: Price",
    "Q12: _ Factors in choosing where to shop\nOption 2: Familiarity",
    "Q12: _ Factors in choosing where to shop\nOption 3: Convenience of location",
    "Q12: _ Factors in choosing where to shop\nOption 4: Quality of products",
    "Q12: _ Factors in choosing where to shop\nOption 5: Variety of products available",
    "Q12: _ Factors in choosing where to shop\nOption 6: Availability of the brands I like",
    "Q12: _ Factors in choosing where to shop\nOption 7: Availability of organic or locally sourced products",
    "Q12: _ Factors in choosing where to shop\nOption 8: Availability of products for a specific diet, e.g. Gluten Free, Vegan",
    "Q12: _ Factors in choosing where to shop\nOption 9: Customer service and support",
    "Q12: _ Factors in choosing where to shop\nOption 10: Store layout and organization",
    "Q12: _ Factors in choosing where to shop\nOption 11: Sales and discounts, special deals or promotions"],
    "Q13: _ Get to grocery store",
    "Q14: _ Time to Grocery",
    ["Q15: _ Grocery Store\nOption 1: Convenience Store (7-Eleven, Shell, CVS, etc.)",
    "Q15: _ Grocery Store\nOption 2: Supermarket (Trader Joes, Kroger, Publix, Safeway, Whole Foods, etc.)",
    "Q15: _ Grocery Store\nOption 3: Big Box/Superstore (Walmart, Target, etc.)",
    "Q15: _ Grocery Store\nOption 4: Warehouse (Sam’s Club, Costco, etc.)",
    "Q15: _ Grocery Store\nOption 5: Discount Store (Dollar Tree, Big Lots, Five Below, etc.)",
    "Q15: _ Grocery Store\nOption 6: Specialty Store (health food store, international food store, etc.)",
    "Q15: _ Grocery Store\nOption 7: Farmer's Market or Open Market",
    "Q15: _ Grocery Store\nOption 8: Online (Instacart, Amazon, ThriveMarket, Misfit Market, etc.)"],
    "Q16: _ Recency",
    "Q19: _ Type of store",
    "Q20: _ Why shop at a supermarket?",
    "Q21: _ Did you plan ahead what you were going to buy?",
    "Q22: _ Did you bring a list with you?",
    "Q23: _ Why no list?",
    "Q24: _ Substitute items",
    "Q25: _ Reasons for substitutions",
    ["Q26: _ Coupons\nOption 1: Coupons",
    "Q26: _ Coupons\nOption 2: Weekly circular",
    "Q26: _ Coupons\nOption 3: Club membership",
    "Q26: _ Coupons\nOption 4: Rewards card",
    "Q26: _ Coupons\nOption 5: Discount program (Senior, teacher, military, etc.)",
    "Q26: _ Coupons\nOption 6: ❌ None of the above"],
    "Q29: _ Planning",
    "Q30: _ Shopping list app",
    "Q31: _ Likes and dislikes\nPOS: What do you like about this app?",
    "Q31: _ Likes and dislikes\nNEG: What do you dislike about this app?",
    "Q32: _ F - Changes and additions",
    "Q33: _ Time spent saving money",
    ["Q35: _ Behavior\nOption 1: ingredients for specific recipes",
    "Q35: _ Behavior\nOption 2: products that I know I can make something out of",
    "Q35: _ Behavior\nOption 3: the same things every time"],
    "Q36: _ Behavior in the supermarket",
    ["Q37: _ What do you typically purchase at Walmart?\nOption 1: Fresh produce",
    "Q37: _ What do you typically purchase at Walmart?\nOption 2: Snacks", 
    "Q37: _ What do you typically purchase at Walmart?\nOption 3: Dairy",
    "Q37: _ What do you typically purchase at Walmart?\nOption 4: Deli items",
    "Q37: _ What do you typically purchase at Walmart?\nOption 6: Meat & seafood",
    "Q37: _ What do you typically purchase at Walmart?\nOption 7: Household supplies",
    "Q37: _ What do you typically purchase at Walmart?\nOption 8: Pet supplies",
    "Q37: _ What do you typically purchase at Walmart?\nOption 9: Other"],
    "Q38: _ Special diet",
    "Q39: _ Nutrition - Yes",
    "Q40: _ Spending",
    "Q41: _ Use of SNAP",
    "Q42: _ Decision factor",
    ["Q43: _ Usage of financial tools\nOption 1: Coupons",
    "Q43: _ Usage of financial tools\nOption 2: Rewards app",
    "Q43: _ Usage of financial tools\nOption 3: Loyalty program or rewards card",
    "Q43: _ Usage of financial tools\nOption 4: Weekly ad circulars",
    "Q43: _ Usage of financial tools\nOption 5: Store branded credit cards",
    "Q43: _ Usage of financial tools\nOption 6: ❌ None of the above"],
    "Q44: _ Competitor price",
    "Q45: _ Savings",
    ["Q47: _ How often do you...\nRow 3: When deciding between two products, I often choose the less  expensive one.\nColumn 1: None of the time",
    'Q47: _ How often do you...\nRow 3: When deciding between two products, I often choose the less  expensive one.\nColumn 2: Rarely',
    'Q47: _ How often do you...\nRow 3: When deciding between two products, I often choose the less  expensive one.\nColumn 3: Some of the time',
    'Q47: _ How often do you...\nRow 3: When deciding between two products, I often choose the less  expensive one.\nColumn 4: Often',
    'Q47: _ How often do you...\nRow 3: When deciding between two products, I often choose the less  expensive one.\nColumn 5: All of the time'],
    ['Q47: _ How often do you...\nRow 1: I buy frozen meals.\nColumn 1: None of the time',
    'Q47: _ How often do you...\nRow 1: I buy frozen meals.\nColumn 2: Rarely',
    'Q47: _ How often do you...\nRow 1: I buy frozen meals.\nColumn 3: Some of the time',
    'Q47: _ How often do you...\nRow 1: I buy frozen meals.\nColumn 4: Often',
    'Q47: _ How often do you...\nRow 1: I buy frozen meals.\nColumn 5: All of the time'],
    ['Q47: _ How often do you...\nRow 2: I go to large grocery stores, where I can buy everything in one place.\nColumn 1: None of the time',
    'Q47: _ How often do you...\nRow 2: I go to large grocery stores, where I can buy everything in one place.\nColumn 2: Rarely',
    'Q47: _ How often do you...\nRow 2: I go to large grocery stores, where I can buy everything in one place.\nColumn 3: Some of the time',
    'Q47: _ How often do you...\nRow 2: I go to large grocery stores, where I can buy everything in one place.\nColumn 4: Often',
    'Q47: _ How often do you...\nRow 2: I go to large grocery stores, where I can buy everything in one place.\nColumn 5: All of the time'],
    ['Q47: _ How often do you...\nRow 4: I buy in bulk.\nColumn 1: None of the time',
    'Q47: _ How often do you...\nRow 4: I buy in bulk.\nColumn 2: Rarely',
    'Q47: _ How often do you...\nRow 4: I buy in bulk.\nColumn 3: Some of the time',
    'Q47: _ How often do you...\nRow 4: I buy in bulk.\nColumn 4: Often',
    'Q47: _ How often do you...\nRow 4: I buy in bulk.\nColumn 5: All of the time'],
    ['Q47: _ How often do you...\nRow 5: I buy food from fresh bars and deli counters in stores.\nColumn 1: None of the time',
    'Q47: _ How often do you...\nRow 5: I buy food from fresh bars and deli counters in stores.\nColumn 2: Rarely',
    'Q47: _ How often do you...\nRow 5: I buy food from fresh bars and deli counters in stores.\nColumn 3: Some of the time',
    'Q47: _ How often do you...\nRow 5: I buy food from fresh bars and deli counters in stores.\nColumn 4: Often',
    'Q47: _ How often do you...\nRow 5: I buy food from fresh bars and deli counters in stores.\nColumn 5: All of the time'],
    ['Q48: _ How often do you...\nRow 1: I buy brand name products.\nColumn 1: None of the time',
    'Q48: _ How often do you...\nRow 1: I buy brand name products.\nColumn 2: Rarely',
    'Q48: _ How often do you...\nRow 1: I buy brand name products.\nColumn 3: Some of the time',
    'Q48: _ How often do you...\nRow 1: I buy brand name products.\nColumn 4: Often',
    'Q48: _ How often do you...\nRow 1: I buy brand name products.\nColumn 5: All of the time'],
    ['Q48: _ How often do you...\nRow 2: I try to buy produce that is in season.\nColumn 1: None of the time',
    'Q48: _ How often do you...\nRow 2: I try to buy produce that is in season.\nColumn 2: Rarely',
    'Q48: _ How often do you...\nRow 2: I try to buy produce that is in season.\nColumn 3: Some of the time',
    'Q48: _ How often do you...\nRow 2: I try to buy produce that is in season.\nColumn 4: Often',
    'Q48: _ How often do you...\nRow 2: I try to buy produce that is in season.\nColumn 5: All of the time'],
    ['Q48: _ How often do you...\nRow 3: When grocery shopping, the items I am looking for are unavailable or out of stock.\nColumn 1: None of the time',
    'Q48: _ How often do you...\nRow 3: When grocery shopping, the items I am looking for are unavailable or out of stock.\nColumn 2: Rarely',
    'Q48: _ How often do you...\nRow 3: When grocery shopping, the items I am looking for are unavailable or out of stock.\nColumn 3: Some of the time',
    'Q48: _ How often do you...\nRow 3: When grocery shopping, the items I am looking for are unavailable or out of stock.\nColumn 4: Often',
    'Q48: _ How often do you...\nRow 3: When grocery shopping, the items I am looking for are unavailable or out of stock.\nColumn 5: All of the time'],
    ['Q48: _ How often do you...\nRow 4: I buy store brand products to save money.\nColumn 1: None of the time',
    'Q48: _ How often do you...\nRow 4: I buy store brand products to save money.\nColumn 2: Rarely',
    'Q48: _ How often do you...\nRow 4: I buy store brand products to save money.\nColumn 3: Some of the time',
    'Q48: _ How often do you...\nRow 4: I buy store brand products to save money.\nColumn 4: Often',
    'Q48: _ How often do you...\nRow 4: I buy store brand products to save money.\nColumn 5: All of the time'],
    'Q49: _ Frustrations',
    ['Q50: Stress-related likert questions\nRow 1: I find it stressful to plan out what I and/or my family is going to eat.\nColumn 1: Strongly disagree',
    'Q50: Stress-related likert questions\nRow 1: I find it stressful to plan out what I and/or my family is going to eat.\nColumn 2: Disagree',
    'Q50: Stress-related likert questions\nRow 1: I find it stressful to plan out what I and/or my family is going to eat.\nColumn 3: Neutral',
    'Q50: Stress-related likert questions\nRow 1: I find it stressful to plan out what I and/or my family is going to eat.\nColumn 4: Agree',
    'Q50: Stress-related likert questions\nRow 1: I find it stressful to plan out what I and/or my family is going to eat.\nColumn 5: Strongly Agree'],
    ['Q50: Stress-related likert questions\nRow 2: I worry about how I am going to pay for groceries.\nColumn 1: Strongly disagree',
    'Q50: Stress-related likert questions\nRow 2: I worry about how I am going to pay for groceries.\nColumn 2: Disagree',
    'Q50: Stress-related likert questions\nRow 2: I worry about how I am going to pay for groceries.\nColumn 3: Neutral',
    'Q50: Stress-related likert questions\nRow 2: I worry about how I am going to pay for groceries.\nColumn 4: Agree',
    'Q50: Stress-related likert questions\nRow 2: I worry about how I am going to pay for groceries.\nColumn 5: Strongly Agree'],
    ['Q50: Stress-related likert questions\nRow 3: I am concerned about the rising cost of groceries.\nColumn 1: Strongly disagree',
    'Q50: Stress-related likert questions\nRow 3: I am concerned about the rising cost of groceries.\nColumn 2: Disagree',
    'Q50: Stress-related likert questions\nRow 3: I am concerned about the rising cost of groceries.\nColumn 3: Neutral',
    'Q50: Stress-related likert questions\nRow 3: I am concerned about the rising cost of groceries.\nColumn 4: Agree',
    'Q50: Stress-related likert questions\nRow 3: I am concerned about the rising cost of groceries.\nColumn 5: Strongly Agree'],
    ['Q50: Stress-related likert questions\nRow 4: Inflation has impacted how I grocery shop.\nColumn 1: Strongly disagree',
    'Q50: Stress-related likert questions\nRow 4: Inflation has impacted how I grocery shop.\nColumn 2: Disagree',
    'Q50: Stress-related likert questions\nRow 4: Inflation has impacted how I grocery shop.\nColumn 3: Neutral',
    'Q50: Stress-related likert questions\nRow 4: Inflation has impacted how I grocery shop.\nColumn 4: Agree',
    'Q50: Stress-related likert questions\nRow 4: Inflation has impacted how I grocery shop.\nColumn 5: Strongly Agree'],
    'Q53: _ Number of prescription drugs', 
    'Q54: _ Drug use in household',
    'Q56: _ Responsible for others',
    ['Q57: _ Who do you pick up prescription drugs for?\nOption 1: Partner or spouse',
    'Q57: _ Who do you pick up prescription drugs for?\nOption 2: Child or children',
    'Q57: _ Who do you pick up prescription drugs for?\nOption 3: Other family members',
    'Q57: _ Who do you pick up prescription drugs for?\nOption 4: Friend or neighbor',
    'Q57: _ Who do you pick up prescription drugs for?\nOption 5: Roommate',
    'Q57: _ Who do you pick up prescription drugs for?\nOption 6: Other'],
    'Q58: _ Drug spend',
    'Q59: _ Pharmacy source',
    'Q60: _ Pharmacy', 
    'Q61: _ Switcher price',
    'Q62: _ Frequency of forgetting to refill prescriptions',
    'Q63: _ Pricing'
]

question_names = [
    "Variable: External: Gender",
    "Variable: External: Age (write-in)",
    "Variable: External: Urban/Rural (self-report)",
    "Variable: External: Annual Household Income (US)",
    "Variable: External: MainRegionName",
    "Variable: External: Food - Main Grocery Shop",
    "1. Who do you grocery shop for?",
    "2. How many people in total do you shop for?",
    '3. How often do you get groceries?',
    '4. How do you shop for groceries?',
    '5. What best describes how you grocery shop in store?',
    '6. How do you find the best deals on groceries when shopping at multiple stores?', 
    '7. How many different stores do you buy groceries at when trying to get the best deal?',
    '8. What best describes why you buy groceries in-store AND online?',
    '9. What are the three most important factors in choosing where to shop?',
    '10. What best describes how you usually get to the grocery store?',
    '11. How long does it typically take you to get to the grocery store?',
    '12. Where do you buy groceries from?',
    '13. When did you most recently shop for groceries in person?',
    '14. What type of store did you buy groceries from during your most recent trip?',
    '15. Of these, what had the biggest impact on your decision to shop at a [supermarket]?',
    '16. Did you plan ahead what you were going to buy?',
    '17. Did you bring a list with you?',
    '18. What best describes why you did NOT bring a list?',
    '19. Did you substitute any of the items on your list?',
    '20. What was the primary reason for substituting items on your grocery list during your last shopping trip?',
    '21. For this shopping trip, did you use any of the following?',
    '22. What best describes how you plan what groceries to buy in general?',
    '23. What do you use to create your shopping lists most often?',
    '24. Thinking about using [list app] for your shopping lists: What do you LIKE about this app?',
    '25. Thinking about using [list app] for your shopping lists: What do you DISLIKE about this app?',
    '26. Is there anything you would change or add to [list app] for shopping lists?',
    '27. How much time do you spend per week looking for ways to save money on groceries (couponing, reading weekly ad circulars, comparing prices, etc.)?',
    '28. While grocery shopping, I buy:',
    '29. While grocery shopping, what do you do more often?', 
    '30. What do you typically purchase?',
    '31. Are you or someone you buy groceries for on a special diet due to a medical condition (Diabetes, Celiac, etc.)?',
    '32. When grocery shopping, do you compare products by looking at the nutrition label and/or ingredient list?',
    '33. How much do you currently spend on groceries per month?',
    '34. Do you use SNAP or food stamp benefits to purchase groceries?',
    '35. What is most important to you when deciding between two products?',
    '36. Which of the following do you use often?',
    '37. Gabor Granger: Would you go to a different store than you normally do for your shopping needs if you knew you would save [Price]?',
    '38. Gabor Granger: Would you go to a more than one store for your shopping needs if you knew it would save you [Price]?',
    '39. I go to large grocery stores, where I can buy everything in one place.',
    '40. When deciding between two products, I often choose the less expensive one.',
    '41. Likert: I buy frozen meals.',
    '42. Likert: I buy in bulk.',
    '43. Likert: I buy food from fresh bars and deli counters in stores.',
    '44. Likert: I buy brand name products.',
    '45. Likert: I try to buy produce that is in season.',
    '46. Likert: When grocery shopping, the items I am looking for are unavailable or out of stock.',
    '47. Likert: I buy store brand products to save money.',
    '48. What frustrates you about grocery shopping?',
    '49. Likert: I find it stressful to plan out what I and/or my family is going to eat.',
    '50. Likert: I worry about how I am going to pay for groceries.',
    '51. Likert: I am concerned about the rising cost of groceries.',
    '52. Likert: Inflation has impacted how I grocery shop.', 
    '53. How many prescription drugs do you take on a regular basis?',
    '54. How many people in your household take prescription drugs on a regular basis?',
    "55. Are you responsible for picking up anyone else's prescription drugs aside from yourself?",
    '56. Who do you pick up prescription drugs for?',
    '57. How much does your household spend on prescription drugs per month?',
    '58. Where does your household fill prescriptions most often?',
    '59. Do you try to do your grocery shopping and pick up prescription drugs in the same trip?',
    '60. Gabor Granger: Would you switch to online delivery for your prescription drugs if you knew it would save you [Price]?',
    '61. Likert: How often do you forget to refill your prescriptions on time?',
    '62. Likert: The price of prescription drugs is too high.'
]

question_types = [
    'Multiple Choice',
    'Number',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Skip',
    'Multiple Answer',
    'Number',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Answer',
    'Number',
    'Multiple Choice',
    'Multiple Answer',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Answer', 
    'Multiple Choice', 
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Choice',
    'Multiple Answer',
    'Multiple Choice',
    'Multiple Choice',
    'Open Ended',
    'Open Ended',
    'Open Ended',
    'Multiple Choice',
    'Multiple Answer',
    'Multiple Choice',
    'Multiple Answer',
    'Multiple Choice',
    'Multiple Choice',
    'Number',
    'Multiple Choice',
    'Multiple Choice',
    'Mulitple Answer',
    'Gabor Granger',
    'Gabor Granger',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer', 
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Open Ended',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Likert - Multiple Answer',
    'Number',
    'Number', 
    'Multiple Choice', 
    'Multiple Answer',
    'Number',
    'Multiple Choice',
    'Multiple Choice', 
    'Gabor Granger',
    'Likert',
    'Likert',
]

def get_question_df():
    q_columns = pd.Series(question_cols)
    q_names = pd.Series(question_names)
    q_types = pd.Series(question_types)

    question_df = pd.concat([q_names, q_types, q_columns], axis=1)
    question_df.rename({0:'Name', 1:'Type', 2:'Columns'}, axis=1, inplace=True)

    return question_df